name: collaborators-only

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  call-collaborators-only-workflow:
    uses: psyb0t/reusable-github-workflows/.github/workflows/collaborators-only-workflow.yml@master
    with:
      close_message: "No PRs. Best security policy ever. Open an issue and I'll fix it myself."
      lock: true
